WIP: Feature/issue4 partitions presentation
Pergamene/project-spiderweb-ui pull request #4
Opened 2019-04-28 15:24 UTC by Pergamene

2019-05-02 14:16 UTC, rhyeen requested changes
For UI changes, we typically have you paste in screenshots that show off the UX changes.  Github lets you paste a screenshot on your clipboard straight into a comment without even having to drag and drop an image.

2019-05-02 14:16 UTC, rhyeen commented on internal_comps/sp_page/src/components/partitions/sp-inner-partition.js
> +    else {
no need for the `else` statement

2019-05-03 01:50 UTC, Pergamene commented
![image](https://user-images.githubusercontent.com/4198105/57116567-31dec500-6d13-11e9-9f89-084b3aa63a02.png)
![image](https://user-images.githubusercontent.com/4198105/57116578-491db280-6d13-11e9-92ba-5588b55fa261.png)
![image](https://user-images.githubusercontent.com/4198105/57116590-5d61af80-6d13-11e9-843e-20c0b62b3235.png)
![image](https://user-images.githubusercontent.com/4198105/57116606-723e4300-6d13-11e9-9257-25839752ccfd.png)
![image](https://user-images.githubusercontent.com/4198105/57116618-841fe600-6d13-11e9-8afa-42b8710bd484.png)

2019-05-04 12:54 UTC, rhyeen commented
What's up with the left margins on the headers?

Let's just change the captions to uppercase, the small-caps looks quirky.

2019-05-04 14:05 UTC, Pergamene commented
![image](https://user-images.githubusercontent.com/4198105/57180126-dad80d80-6e42-11e9-804d-6328f805b964.png)
They were two different screenshots so I just got more margin in the header image.
![image](https://user-images.githubusercontent.com/4198105/57180170-4ae69380-6e43-11e9-85dd-89ff0f4df09c.png)

2019-05-04 21:49 UTC, merged