WIP: Issue/6 detail editing
Pergamene/project-spiderweb-ui pull request #7
Opened 2019-05-12 05:25 UTC by Pergamene

2019-05-13 17:45 UTC, rhyeen requested changes

2019-05-13 17:45 UTC, rhyeen commented on internal_comps/sp_page/src/components/page-action/sp-page-action-footer.js
> +      // @ISSUE: add one for detail
Remove comment

2019-05-13 17:45 UTC, rhyeen commented on internal_comps/sp_page/src/components/page-parts/edit/sp-page-title-edit.js
> +// @ISSUE: you'll want your own *-edit.js file for sp-page-detail.js
remove comment

2019-05-13 17:45 UTC, rhyeen commented on internal_comps/sp_page/src/components/page-parts/sp-page-overview.js
> +import { selectPageOverview, PAGE_SELECTION_ACTION_EDIT, PAGE_SECTION_TYPE_DETAIL, PAGE_SECTION_TYPE_OVERVIEW } from '../../state/action.js';
don't need `PAGE_SECTION_TYPE_DETAIL` (I believe)

2019-05-14 19:17 UTC, Pergamene commented
![image](https://user-images.githubusercontent.com/4198105/57725501-8571dc80-764a-11e9-909c-e6d93f50280f.png)
![image](https://user-images.githubusercontent.com/4198105/57725526-96225280-764a-11e9-8b95-cb0c12794944.png)

2019-05-14 21:25 UTC, rhyeen approved these changes

2019-05-14 21:25 UTC, merged